name: Pull Request

on: pull_request

jobs:
  test:
    name: Test CVE Generation
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install ./
      - name: Run Tests
        run: test_cve_generation

  check:
    name: Check Advisories
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install ./
      - name: Run Advisories Checks
        run: check_advisories --all
